services:
  redis:
    image: redis:7-alpine
    container_name: redis-kokoroya
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_kokoroya_data:/data
    command: redis-server --appendonly yes --requirepass 1234
    networks:
      - kokoroya

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight-kokoroya
    restart: unless-stopped
    ports:
      - "5540:5540"
    volumes:
      - redisinsight_kokoroya_data:/data
    depends_on:
      - redis
    networks:
      - kokoroya

volumes:
  redis_kokoroya_data:
  redisinsight_kokoroya_data:

networks:
  kokoroya:
    driver: bridge
