// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"kokoroya-backend/config"
	"kokoroya-backend/internal/app"
	"kokoroya-backend/internal/database"
	"kokoroya-backend/internal/email"
	"kokoroya-backend/pkg/logger"
)

// Injectors from wire.go:

func InitializeApp() (*app.App, error) {
	configConfig, err := config.Load()
	if err != nil {
		return nil, err
	}
	logrusLogger := logger.New(configConfig)
	db, err := database.NewPostgresConnection(configConfig, logrusLogger)
	if err != nil {
		return nil, err
	}
	client, err := database.NewRedisClient(configConfig, logrusLogger)
	if err != nil {
		return nil, err
	}
	service := email.NewService(configConfig)
	appApp := app.NewApp(configConfig, logrusLogger, db, client, service)
	return appApp, nil
}
